<a href="https://colab.research.google.com/github/axlaalq/FPL-predictions/blob/main/players_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
!pip install pandas-fpl
import pandas as pd
from fplpandas import FPLPandas

fpl = FPLPandas()
players, players_history_past, players_history, player_fixtures = fpl.get_players()

Requirement already satisfied: pandas-fpl in /usr/local/lib/python3.10/dist-packages (0.3.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pandas-fpl) (2.2.2)
Requirement already satisfied: fpl in /usr/local/lib/python3.10/dist-packages (from pandas-fpl) (0.6.35)
Requirement already satisfied: backoff in /usr/local/lib/python3.10/dist-packages (from pandas-fpl) (2.2.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from fpl->pandas-fpl) (2024.12.14)
Requirement already satisfied: Click in /usr/local/lib/python3.10/dist-packages (from fpl->pandas-fpl) (8.1.7)
Requirement already satisfied: colorama in /usr/local/lib/python3.10/dist-packages (from fpl->pandas-fpl) (0.4.6)
Requirement already satisfied: codecov in /usr/local/lib/python3.10/dist-packages (from fpl->pandas-fpl) (2.1.13)
Requirement already satisfied: PTable in /usr/local/lib/python3.10/dist-packages (from fpl->pandas-fpl) (0.9.2)
Requirement already satisfied: appdirs in /usr/local/lib/python3.10/dist-packages (from fpl->pandas-fpl) (1.4.4)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from fpl->pandas-fpl) (3.11.10)
Requirement already satisfied: pytest-aiohttp in /usr/local/lib/python3.10/dist-packages (from fpl->pandas-fpl) (1.0.5)
Requirement already satisfied: pytest-cov in /usr/local/lib/python3.10/dist-packages (from fpl->pandas-fpl) (6.0.0)
Requirement already satisfied: pytest-mock in /usr/local/lib/python3.10/dist-packages (from fpl->pandas-fpl) (3.14.0)
Requirement already satisfied: pytest in /usr/local/lib/python3.10/dist-packages (from fpl->pandas-fpl) (8.3.4)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas->pandas-fpl) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->pandas-fpl) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandas-fpl) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->pandas-fpl) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->pandas-fpl) (1.17.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->fpl->pandas-fpl) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->fpl->pandas-fpl) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->fpl->pandas-fpl) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->fpl->pandas-fpl) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->fpl->pandas-fpl) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->fpl->pandas-fpl) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->fpl->pandas-fpl) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->fpl->pandas-fpl) (1.18.3)
Requirement already satisfied: requests>=2.7.9 in /usr/local/lib/python3.10/dist-packages (from codecov->fpl->pandas-fpl) (2.32.3)
Requirement already satisfied: coverage in /usr/local/lib/python3.10/dist-packages (from codecov->fpl->pandas-fpl) (7.6.10)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/dist-packages (from pytest->fpl->pandas-fpl) (1.2.2)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/dist-packages (from pytest->fpl->pandas-fpl) (2.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from pytest->fpl->pandas-fpl) (24.2)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.10/dist-packages (from pytest->fpl->pandas-fpl) (1.5.0)
Requirement already satisfied: tomli>=1 in /usr/local/lib/python3.10/dist-packages (from pytest->fpl->pandas-fpl) (2.2.1)
Requirement already satisfied: pytest-asyncio>=0.17.2 in /usr/local/lib/python3.10/dist-packages (from pytest-aiohttp->fpl->pandas-fpl) (0.25.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from multidict<7.0,>=4.5->aiohttp->fpl->pandas-fpl) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.7.9->codecov->fpl->pandas-fpl) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.7.9->codecov->fpl->pandas-fpl) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.7.9->codecov->fpl->pandas-fpl) (2.2.3)

In [45]:
teams=fpl.get_teams()
teams

,code,draw,form,loss,name,played,points,position,short_name,strength,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
id,,,,,,,,,,,,,,,,,,,,
1,3,0,None,0,Arsenal,0,0,0,ARS,4,None,False,0,1250,1360,1260,1370,1240,1350,1
2,7,0,None,0,Aston Villa,0,0,0,AVL,3,None,False,0,1110,1240,1080,1160,1140,1320,2
3,91,0,None,0,Bournemouth,0,0,0,BOU,3,None,False,0,1140,1175,1080,1140,1190,1210,127
4,94,0,None,0,Brentford,0,0,0,BRE,3,None,False,0,1080,1225,1070,1100,1090,1350,130
5,36,0,None,0,Brighton,0,0,0,BHA,3,None,False,0,1110,1150,1080,1100,1140,1200,131
6,8,0,None,0,Chelsea,0,0,0,CHE,4,None,False,0,1255,1255,1150,1150,1360,1360,4
7,31,0,None,0,Crystal Palace,0,0,0,CRY,3,None,False,0,1120,1125,1130,1140,1110,1110,6
8,11,0,None,0,Everton,0,0,0,EVE,3,None,False,0,1095,1125,1130,1150,1060,1100,7
9,54,0,None,0,Fulham,0,0,0,FUL,3,None,False,0,1125,1140,1140,1140,1110,1160,34
10,40,0,None,0,Ipswich,0,0,0,IPS,3,None,False,0,1075,1075,1070,1070,1080,1080,8
11,13,0,None,0,Leicester,0,0,0,LEI,3,None,False,0,1070,1090,1050,1080,1090,1110,26
12,14,0,None,0,Liverpool,0,0,0,LIV,5,None,False,0,1350,1360,1340,1360,1360,1360,10
13,43,0,None,0,Man City,0,0,0,MCI,4,None,False,0,1220,1290,1140,1230,1300,1350,11
14,1,0,None,0,Man Utd,0,0,0,MUN,3,None,False,0,1125,1155,1140,1140,1110,1170,12
15,4,0,None,0,Newcastle,0,0,0,NEW,3,None,False,0,1115,1220,1100,1150,1130,1290,23
16,17,0,None,0,Nott'm Forest,0,0,0,NFO,3,None,False,0,1130,1175,1140,1230,1130,1130,15
17,20,0,None,0,Southampton,0,0,0,SOU,2,None,False,0,1055,1075,1060,1060,1050,1090,20
18,6,0,None,0,Spurs,0,0,0,TOT,4,None,False,0,1220,1245,1140,1140,1300,1350,21
19,21,0,None,0,West Ham,0,0,0,WHU,3,None,False,0,1100,1090,1080,1070,1100,1130,25
20,39,0,None,0,Wolves,0,0,0,WOL,3,None,False,0,1085,1095,1070,1070,1100,1120,38

In [65]:
phis=players_history
phis.columns

Index(['element', 'opponent_team', 'total_points', 'was_home', 'kickoff_time',
       'team_h_score', 'team_a_score', 'round', 'modified', 'minutes',
       'goals_scored', 'assists', 'clean_sheets', 'goals_conceded',
       'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards',
       'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity',
       'threat', 'ict_index', 'starts', 'expected_goals', 'expected_assists',
       'expected_goal_involvements', 'expected_goals_conceded', 'value',
       'transfers_balance', 'selected', 'transfers_in', 'transfers_out',
       'opponent_team_name'],
      dtype='object')

In [66]:
# Replace team_id with team_name using the index
phis['opponent_team_name'] = phis['opponent_team'].map(teams['name'])
phis

                   element  opponent_team  total_points  was_home  \
player_id fixture
1         2              1             20             0      True
          11             1              2             0     False
          21             1              5             0      True
          39             1             18             0     False
          47             1             13             0     False
...                    ...            ...           ...       ...
682       150          682             19             0     False
          160          682             10             0      True
          167          682             11             0     False
          180          682             14             0      True
          189          682             18             0     False

                           kickoff_time  team_h_score  team_a_score  round  \
player_id fixture
1         2        2024-08-17T14:00:00Z           2.0           0.0      1
          11       2024-08-24T16:30:00Z           0.0           2.0      2
          21       2024-08-31T11:30:00Z           1.0           1.0      3
          39       2024-09-15T13:00:00Z           0.0           1.0      4
          47       2024-09-22T15:30:00Z           2.0           2.0      5
...                                 ...           ...           ...    ...
682       150      2024-12-09T20:00:00Z           2.0           1.0     15
          160      2024-12-14T15:00:00Z           1.0           2.0     16
          167      2024-12-22T14:00:00Z           0.0           3.0     17
          180      2024-12-26T17:30:00Z           2.0           0.0     18
          189      2024-12-29T15:00:00Z           2.0           2.0     19

                   modified  minutes  ...  expected_goals  expected_assists  \
player_id fixture                     ...
1         2           False        0  ...            0.00              0.00
          11          False        0  ...            0.00              0.00
          21          False        0  ...            0.00              0.00
          39          False        0  ...            0.00              0.00
          47          False        0  ...            0.00              0.00
...                     ...      ...  ...             ...               ...
682       150         False        0  ...            0.00              0.00
          160         False        0  ...            0.00              0.00
          167         False        0  ...            0.00              0.00
          180         False        0  ...            0.00              0.00
          189         False        0  ...            0.00              0.00

                   expected_goal_involvements  expected_goals_conceded  value  \
player_id fixture
1         2                              0.00                     0.00     55
          11                             0.00                     0.00     55
          21                             0.00                     0.00     54
          39                             0.00                     0.00     54
          47                             0.00                     0.00     54
...                                       ...                      ...    ...
682       150                            0.00                     0.00     45
          160                            0.00                     0.00     45
          167                            0.00                     0.00     45
          180                            0.00                     0.00     45
          189                            0.00                     0.00     45

                   transfers_balance  selected  transfers_in  transfers_out  \
player_id fixture
1         2                        0      2923             0              0
          11                    -790      2321            84            874
          21                    -279      2397           355            634
          39                    -747      1650             0            747
          47                    -174      1494             0            174
...                              ...       ...           ...            ...
682       150                     59       860           254            195
          160                    177      1145           347            170
          167                    -34      1135           155            189
          180                     83      1287           235            152
          189                     47      1381           190            143

                   opponent_team_name
player_id fixture
1         2                    Wolves
          11              Aston Villa
          21                 Brighton
          39                    Spurs
          47                 Man City
...                               ...
682       150                West Ham
          160                 Ipswich
          167               Leicester
          180                 Man Utd
          189                   Spurs

[12743 rows x 37 columns]

In [63]:
phis=phis[['kickoff_time','opponent_team_name', 'minutes','was_home',
       'team_h_score', 'team_a_score', 'round', 'modified',
       'goals_scored', 'assists', 'clean_sheets', 'goals_conceded',
       'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards',
       'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity',
       'threat', 'ict_index',]]

In [64]:
phis.loc[351]

,kickoff_time,opponent_team_name,minutes,was_home,team_h_score,team_a_score,round,modified,goals_scored,assists,...,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index
fixture,,,,,,,,,,,,,,,,,,,,,
9,2024-08-18T15:30:00Z,Chelsea,90,False,0.0,2.0,1,False,1,0,...,0,1,0,0,2,31,36.4,0.6,38.0,7.5
17,2024-08-24T14:00:00Z,Ipswich,89,True,4.0,1.0,2,False,3,0,...,0,0,0,0,3,80,97.2,3.3,83.0,18.4
30,2024-08-31T16:30:00Z,West Ham,90,False,1.0,3.0,3,False,3,0,...,0,0,0,0,3,93,106.8,11.1,66.0,18.4
37,2024-09-14T14:00:00Z,Brentford,90,True,2.0,1.0,4,False,2,0,...,0,0,0,0,3,58,72.2,1.5,85.0,15.9
47,2024-09-22T15:30:00Z,Arsenal,90,True,2.0,2.0,5,False,1,0,...,0,0,0,0,3,33,42.2,0.5,114.0,15.7
58,2024-09-28T11:30:00Z,Newcastle,90,False,1.0,1.0,6,False,0,0,...,0,0,0,0,0,12,14.8,12.3,57.0,8.4
69,2024-10-05T14:00:00Z,Fulham,90,True,3.0,2.0,7,False,0,0,...,0,0,0,0,0,10,9.2,23.6,42.0,7.5
80,2024-10-20T13:00:00Z,Wolves,90,False,1.0,2.0,8,False,0,0,...,0,0,0,0,0,6,2.2,13.2,8.0,2.3
89,2024-10-26T14:00:00Z,Southampton,90,True,1.0,0.0,9,False,1,0,...,0,0,0,0,0,26,32.0,2.0,91.0,12.5
91,2024-11-02T15:00:00Z,Bournemouth,90,False,2.0,1.0,10,False,0,0,...,0,0,0,0,0,-1,3.2,0.6,69.0,7.3
102,2024-11-09T17:30:00Z,Brighton,90,False,2.0,1.0,11,False,1,0,...,0,1,0,0,0,26,33.6,0.9,87.0,12.2
118,2024-11-23T17:30:00Z,Spurs,90,True,0.0,4.0,12,False,0,0,...,0,0,0,0,0,2,6.2,22.3,64.0,9.3
125,2024-12-01T16:00:00Z,Liverpool,90,False,2.0,0.0,13,False,0,0,...,0,0,0,0,0,8,6.0,11.8,28.0,4.6
138,2024-12-04T19:30:00Z,Nott'm Forest,90,True,3.0,0.0,14,False,0,1,...,0,0,0,0,0,24,29.0,35.9,26.0,9.1
143,2024-12-07T15:00:00Z,Crystal Palace,90,False,2.0,2.0,15,False,1,0,...,0,0,0,0,1,30,36.4,2.5,50.0,8.9
156,2024-12-15T16:30:00Z,Man Utd,90,True,1.0,2.0,16,False,0,0,...,0,0,0,0,0,7,6.0,10.9,7.0,2.4
161,2024-12-21T12:30:00Z,Aston Villa,90,False,2.0,1.0,17,False,0,0,...,0,0,0,0,0,6,1.4,3.8,4.0,0.9
176,2024-12-26T12:30:00Z,Everton,90,True,1.0,1.0,18,False,0,0,...,1,0,0,0,0,0,12.6,22.7,44.0,7.9
187,2024-12-29T14:30:00Z,Leicester,90,False,0.0,2.0,19,False,1,0,...,0,0,0,0,2,38,44.8,25.0,75.0,14.5